services:
  - type: web
    name: facilita-sp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: DATABASE_URL
        sync: false   # você preenche manualmente no painel do Render
